# Generated by Django 5.0.2 on 2024-03-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avator',
            field=models.ImageField(default='avator.jpg', null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
