# Generated by Django 5.0.2 on 2024-03-27 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_user_bio_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avator',
            field=models.ImageField(blank=True, default='avator.jpg', null=True, upload_to='avators/'),
        ),
    ]
